# Generated by Django 6.1.1 on 2026-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_players', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('price', models.DecimalField()),
                ('max_players', models.IntegerField()),
            ],
        ),
    ]
